name: Google Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  google-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc g++ cmake make ninja-build
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8

      - name: Build
        run: |
          cd tests
          mkdir cmake-build-unit-tests
          cd cmake-build-unit-tests
          cmake -G "Ninja" ..
          ninja

      - name: Run tests
        run: |
          cd tests/cmake-build-unit-tests
          ctest
